#+ summary: Gets 11 random triples from Wikidata
#+ endpoint: https://query.wikidata.org/sparql

#Cats
SELECT ?item ?itemLabel 
WHERE 
{
  ?item wdt:P31 wd:Q146.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
LIMIT 11
